################################
#
# CheatEye Configuration
#
################################

# Watch directory. not file. please input log directory.
watchDir: "/var/www/api/cheateye/v1/logs/"

