name: CheatEye
main: tk.rht0910.cheateye.CheatEye
version: 0.1
depend: [TomeitoLib, ProtocolLib]
softdepend: [MCBans]

commands:
   cheateye:
      description: Root command of CheatEye.
      usage: /<command> [args]
      permission: cheateye.help
      aliases: [ce]

permissions:
    cheateye.*:
      description: Gives access to all CheatEye commands